[package]
name = "improve"
version = "0.1.0"
authors = ["louis <louis.roc@gmail.com>"]
edition = "2018"

[dependencies]
rustfft = '>= 3.0.0'
itertools = '>= 0.8.0'
clampf = '>= 0.1.1'
cpal = '>= 0.8.2'
clap = '>= 2.32.0'
sdl2 = '>= 0.32.1'
