[package]
name = "improve"
version = "0.1.0"
authors = ["louis <louis.roc@gmail.com>"]
edition = "2018"

[dependencies]
rustfft = '>= 3.0.0'
itertools = '>= 0.8.0'
clap = '>= 2.32.0'

[dependencies.sdl2]
version = '0.32.0'
features = ["ttf"]
